### ISSUE TITLE
reportportal_client.errors.ResponseError: Error during updating TestItem null

### ISSUE THREAD

**Issue by DKorytkin** [reportportal/agent-python-pytest#27] opened 2017-06-26 13:26 UTC
```python
============================================================================ test session starts ============================================================================
platform linux -- Python 3.5.2, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/dkorytkin/PycharmProjects/test/tests, inifile: pytest.ini
plugins: reportportal-1.0.0, env-0.6.2, allure-pytest-2.0.0b1
collected 1 items 

tests/test_open_page.py .

========================================================================= 1 passed in 2.27 seconds ==========================================================================
Traceback (most recent call last):
  File "/home/dkorytkin/.local/share/virtualenvs/test-9Ahk-nxU/lib/python3.5/site-packages/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/test-9Ahk-nxU/lib/python3.5/site-packages/reportportal_client/service.py", line 179, in finish_test_item
    return _get_msg(r)
  File "/home/dkorytkin/.local/share/virtualenvs/test-9Ahk-nxU/lib/python3.5/site-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/home/dkorytkin/.local/share/virtualenvs/test-9Ahk-nxU/lib/python3.5/site-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Error during updating TestItem null
```

**Comment by krasoffski** [comment] 2017-07-04 08:35
Without steps/snippet it will be hard to reproduce this problem and fix them.

**Comment by DzmitryHumianiuk** [comment] 2017-07-07 15:54
@DKorytkin could you please share steps/snippet?

**Comment by DzmitryHumianiuk** [comment] 2018-07-18 13:54
@DKorytkin closing because of missing details.
plz open new issue, if this still actual for you

**Closed by DzmitryHumianiuk** 2018-07-18 13:54 UTC
Labels: wontfix
