### ISSUE TITLE
pytest-reportportal hangs approx 1 out of 3 launches

### ISSUE THREAD

**Issue by ringods** [reportportal/agent-python-pytest#74] opened 2018-08-06 09:12 UTC
I am experiencing flakey behaviour with `pytest-reportportal`. This `pytest` plugin is active when running tests in Jenkins. The test results are then pushed to ReportPortal. Both systems run in the same set of machines on the company AWS account.

The unit test suite for one of our projects contains 2540 tests at the time of writing. Since we also have a precommit trigger on this project, I know for sure that all unit tests succeed.

When pushing the test results from Jenkins to RP, 1 out of 3 executions (on average) seem to hang. I have to kill the ongoing Jenkins run and then `Force finish` the launch on RP. This is not maintainable.

I would like to add more info, but the Jenkins console just sits there. The last line being reported was `pytest` saying that all tests ran correctly:

```
========================= 2540 passed in 31.49 seconds =========================
```

**Comment by ailjushkin** [comment] 2018-08-08 06:01
It is more likely the Report Portal problem I had previously faced - sometimes it's API microservice fails to process a request and answers with 404 not found error code. You should monitor a docker log for HTTP error codes to catch that moment. Since some of test items did not finish properly, the launch itself cannot be closed as it still has in progress status.

As a workaround, I can only suggest you to force close test items of the whole launch, Report Portal API has such method.

**Comment by ringods** [comment] 2018-08-08 07:42
@ailjushkin I scanned the docker logs of last Monday (6 Aug) where multiple of these hangs occurred. The logs don't show any HTTP errors. Only logs from triggers to clean screenshots and alike.

I'm also pushing test results from another project with a custom written Javascript agent and that behaves perfectly. Given it is only the Python agent which gives me problems, I doubt it is RP. Could you please have a look at the Python agent implementation?

**Comment by krasoffski** [comment] 2018-08-08 09:11
I would add enough debug logging and only than tried to reproduce issue again (I am not sure about logging coverage now).

**Comment by ringods** [comment] 2018-08-21 08:00
@ailjushkin @krasoffski I was able to reproduce locally. Here is the client side log from the pytest agent when pressing Ctrl-C while it hangs:

```
============================================================= 2740 passed in 41.17 seconds =============================================================
^CDEBUG:reportportal_client.service_async:Processing log item: {'time': '1534837681564', 'message': "SpecExample('it is component','<mamba.runnable.ExecutionContext object at 0x10a8a39e8>').runtest()", 'level': 'INFO', 'attachment': None}
Traceback (most recent call last):
  File "/Users/ringods/Projects/ontoforce/metis/metis/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/_pytest/config.py", line 61, in main
    return config.hook.pytest_cmdline_main(config=config)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/ringods/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/ringods/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/reportportal_client/service_async.py", line 86, in _monitor
    self.handle(record)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/reportportal_client/service_async.py", line 54, in handle
    handler(record)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/reportportal_client/service_async.py", line 197, in process_item
    self.queue.qsize())
AttributeError: 'NoneType' object has no attribute 'qsize'
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__

    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/_pytest/main.py", line 138, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/_pytest/main.py", line 133, in wrap_session
    config._ensure_unconfigure()
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/_pytest/config.py", line 919, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pytest_reportportal/plugin.py", line 106, in pytest_unconfigure
    config.py_test_service.terminate_service()
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/pytest_reportportal/service.py", line 72, in terminate_service
    self.RP.terminate()
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/reportportal_client/service_async.py", line 159, in terminate
    self.listener.stop(nowait)
  File "/Users/ringods/Projects/ontoforce/metis/metis/lib/python3.6/site-packages/reportportal_client/service_async.py", line 109, in stop
    self._thread.join()
  File "/Users/ringods/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/ringods/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

Does this help debugging?

**Comment by rplevka** [comment] 2018-10-30 09:40
I experience this as well in our production environment and I figured out that there is a deadlock happening on the client side which prevents the py.test run to finish (thus jenkins job never finishes).

If one uses `rp_ignore_errors = True` then if a connection is somehow lost during the `py.test` execution, it continues just fine up until the point it tries to stop the launch.
this obviously spawns a [service.terminate()](https://github.com/reportportal/client-Python/blob/master/reportportal_client/service_async.py#L167) which acquires a `threading.Lock`, effectively blocking anything else until it finishes the execution - the tricky part comes when this method call which holds the lock directly [calls the error_handler](https://github.com/reportportal/client-Python/blob/master/reportportal_client/service_async.py#L189), which is defined in the py.test plugin [here](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/service.py#L102).
Note, that this error handler directly calls [service.terminate(nowait=True)](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/service.py#L103) again, which effectively introduces a deadlock, since the called method tries to acquire the same lock which is already held by its parent!

Removing [the line](https://github.com/reportportal/agent-python-pytest/blob/master/pytest_reportportal/service.py#L103) seems to solve the issue and makes the py.test to correctly terminate the session (finish the launch on RP) and finish without any errors.

I'm not sure what is the purpose of the current implementation of the error_handler so I can't tell this is the correct solution to a problem (it might cause trouble in different sscenarios) but I believe it is a hint at least. @krasoffski, This seemed to be introduced as a part of 'inglorious' RP_hierarchy commit, so perhaps we should handle this PoC differently if no hierarchy is enabled?

**Comment by krasoffski** [comment] 2018-10-30 13:54
There is huge traceback which is enough to debug issue. Thank you @ringods.
Unfortunately I short of free time last mounts to keep my eyes on what is going on with python agents. :-(

**Comment by iivanou** [comment] 2020-03-19 14:09
Should not be an issue anymore since a non-blocking request handler that hangs on termination is not used.

**Closed by iivanou** 2020-03-19 14:09 UTC
