### ISSUE TITLE
Log attachments being attached to the wrong test function with Pytest

### ISSUE THREAD

**Issue by allan-silverstein** [reportportal/agent-python-pytest#241] opened 2020-11-19 23:31 UTC
I had originally posted this issue under ReportPortal but I believe it belongs here:

This something that has been happening to me for a while when initiating the tests from a particular system. In this case, I have 17 test functions spread across 8 modules. I'm running them using the pytest markers flag (-m ). After each test function runs, the following code is called to send detailed log files to report portal:

def attach_session_logs(testinfo,rp_logger):
    for dev in testinfo['log_files']: # loop through session log file names
        dirpath = os.getcwd()

        # get log file in current working directory
        log_dir = Path(dirpath,testinfo['log_files'][dev]) 

        # open log file and send contents as an attachment to reportportal
        with open(log_dir) as file: 
            contents = file.read()
            rp_logger.info("Session Log Attachment - " + testinfo['log_files'][dev],
                                     attachment={"name": testinfo['log_files'][dev],
                                    "data": contents, "mime": "text/plain"})
After some troubleshooting between initiating the pytest test between two different systems. I noticed it only happens on the system with specific versions of reportportal-client.

When the versions are this, everything works fine:
pytest-reportportal==5.0.3
reportportal-client==5.0.3

Anything newer and the problem happens:
I've tried with this:
pytest-reportportal==5.0.6
reportportal-client==5.0.6
and this:
pytest-reportportal==5.0.3
reportportal-client==5.0.5
and probably a few other combinations.

Before troubleshooting the pytest modules I upgraded reportportal from 5.2.2 to the lateset 5.3.2 (what I'm running now) but that had no effect.

***Expected behavior***
Each test function result should have its own log files in ReportPortal as such:

![image](https://user-images.githubusercontent.com/18428970/99736964-51744480-2a95-11eb-8861-789fd96805b1.png)

Report Portal is running with Docker Compose on ubuntu 16.0.4

**Comment by iivanou** [comment] 2020-11-20 09:04
Nothing's changed in that functionality since release 5.0.3 both in the agent and in the client. Try running your tests with the DEBUG log level. If you are not able to find out the root cause, then share those logs here and I will try to help you.

**Comment by vlbolotin** [comment] 2020-12-10 11:51
I'm observing the same issue as soon as updated both client an agent from version 5.0.3
I've tried both 5.0.5 and 5.0.6
It looks like attachments are added in bulk at some point of execution so that attachments from already executed tests from other modules are attached at once to the one test.
In the release notes to 5.0.6 for agent there is a note - Fixed missed log_batch_size in init_service();
Just wondering, may it be somehow related? At which point it was missed and etc

**Comment by iivanou** [comment] 2020-12-10 12:37
The workaround is to add `rp_log_batch_size = 1` into the pytest.ini file.

**Comment by vlbolotin** [comment] 2020-12-10 13:01
Workaround has helped. Thanks a lot!

**Comment by allan-silverstein** [comment] 2020-12-10 15:03
I will try this later this week.  Hope it helps me as well...

**Comment by iivanou** [comment] 2021-03-02 13:11
Closing this one, the log batches mechanism has been fixed in client version 5.0.9.

**Closed by iivanou** 2021-03-02 13:11 UTC
