### ISSUE TITLE
Tags do not appear to work

### ISSUE THREAD

**Issue by dijital20** [reportportal/agent-python-pytest#174] opened 2020-03-30 19:54 UTC
Pytest.ini code:
```ini
[pytest]
markers =
    marker1: First marker
    marker2: Second marker
    marker3: Third marker

;Logging settings
log_cli = True
log_level = DEBUG
log_format = %(asctime)s %(levelname)s %(module)s[%(lineno)d] %(message)s

;Report Portal settings
rp_uuid = <my UUID>
rp_endpoint = <my instance>
rp_project = <my project>
rp_launch = Report Portal Test
rp_launch_tags = ThisIsATestTag
rp_launch_description = Test if tagging works in pytest-reportportal
rp_ignore_errors = False
```

Unit test code
```python
import pytest


@pytest.mark.marker1
@pytest.mark.marker2
def test1():
    # This should pass and show marker1 and marker2 for tags.
    assert True

@pytest.mark.marker2
@pytest.mark.marker3
def test2():
    # Test should pass and show marker2 and marker3 for tags.
    assert True

@pytest.mark.marker1
@pytest.mark.marker3
def test_failing_test():
    # Test should fail and show marker1 and marker3 for tags.
    assert False
```

Debug logging output
```
C:\Users\my_user\Projects\Scratch\rp_test_project>python3 -m pytest --reportportal

------------------------------------------------ live log sessionstart ------------------------------------------------
14:40:43 DEBUG service[106] ReportPortal - Init service: endpoint=<my instance>, project=<my project>, uuid=<my UUID>
14:40:43 DEBUG connectionpool[205] Starting new HTTP connection (1): <my instance>
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "GET /api/v1/<my project>/settings HTTP/1.1" 200 676
14:40:43 DEBUG service[269] settings
14:40:43 DEBUG service[142] ReportPortal - Start launch: equest_body={'name': 'Report Portal Test', 'start_time': '1585597243854', 'description': 'Test if tagging works in pytest-reportportal', 'mode': None}
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/launch HTTP/1.1" 201 59
14:40:43 DEBUG service[175] start_launch - ID: 61119323-de50-40ca-b286-45dd09094ed4
14:40:43 DEBUG service[144] ReportPortal - Launch started: id=61119323-de50-40ca-b286-45dd09094ed4
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-5.4.1, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\my_user\Projects\Scratch\rp_test_project, inifile: pytest.ini
plugins: reportportal-5.0.0
collected 3 items
------------------------------------------------- live log collection -------------------------------------------------
14:40:43 DEBUG service[223] ReportPortal - Start Suite: request_body={'name': ':\\test_rp.py', 'description': None, 'start_time': '1585597243907', 'item_type': 'SUITE', 'parent_item_id': None}
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/item HTTP/1.1" 201 45
14:40:43 DEBUG service[236] start_test_item - ID: 1e9b68ae-327a-4a55-b09b-13e944887694
14:40:43 DEBUG service[239] ReportPortal - Start TestItem: request_body={'name': 'test1', 'description': None, 'start_time': '1585597243919', 'item_type': 'TEST', 'parent_item_id': '1e9b68ae-327a-4a55-b09b-13e944887694', 'parameters': {}}
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/item/1e9b68ae-327a-4a55-b09b-13e944887694 HTTP/1.1" 201 45
14:40:43 DEBUG service[236] start_test_item - ID: eda44e65-417a-4362-8bd9-cceec516ec51

test_rp.py::test1 PASSED                                                                                         [ 33%]
--------------------------------------------------- live log finish ---------------------------------------------------
14:40:43 DEBUG service[281] ReportPortal - Finish TestItem: request_body={'end_time': '1585597243935', 'status': 'PASSED', 'issue': {'issue_type': 'ti001'}, 'item_id': 'eda44e65-417a-4362-8bd9-cceec516ec51'}

14:40:43 DEBUG service[239] ReportPortal - Start TestItem: request_body={'name': '<my project>2', 'description': None, 'start_time': '1585597243937', 'item_type': 'TEST', 'parent_item_id': '1e9b68ae-327a-4a55-b09b-13e944887694', 'parameters': {}}
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/item/1e9b68ae-327a-4a55-b09b-13e944887694 HTTP/1.1" 201 45
14:40:43 DEBUG service[236] start_test_item - ID: b9097de7-d776-48fd-9b04-ab8796c7ffa9

test_rp.py::test2 PASSED                                                                                         [ 66%]
--------------------------------------------------- live log finish ---------------------------------------------------
14:40:43 DEBUG service[281] ReportPortal - Finish TestItem: request_body={'end_time': '1585597243953', 'status': 'PASSED
', 'issue': {'issue_type': 'ti001'}, 'item_id': 'b9097de7-d776-48fd-9b04-ab8796c7ffa9'}

14:40:43 DEBUG service[239] ReportPortal - Start TestItem: request_body={'name': 'test_failing_test', 'description': Non
e, 'start_time': '1585597243954', 'item_type': 'TEST', 'parent_item_id': '1e9b68ae-327a-4a55-b09b-13e944887694', 'parame
ters': {}}
14:40:43 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/item/1e9b68ae-327a-4a55-b09b-13e94488769
4 HTTP/1.1" 201 45
14:40:43 DEBUG service[236] start_test_item - ID: 51e980d8-be48-445c-94fa-c98dabcc5714

test_rp.py::test_failing_test
---------------------------------------------------- live log call ----------------------------------------------------
14:40:44 DEBUG connectionpool[393] http://<my instance>:8080 "POST /api/v2/<my project>/log HTTP/1.1" 201 61
14:40:44 DEBUG service[351] log_batch - ID: 51e980d8-be48-445c-94fa-c98dabcc5714
14:40:44 DEBUG service[352] log_batch response: {"responses":[{"id":"bfe0ff0c-fe58-433c-bd4b-afaa043dbe52"}]}
FAILED                                                                   [100%]
--------------------------------------------------- live log finish ---------------------------------------------------
14:40:44 DEBUG service[281] ReportPortal - Finish TestItem: request_body={'end_time': '1585597244032', 'status': 'FAILED
', 'issue': {'issue_type': 'ti001'}, 'item_id': '51e980d8-be48-445c-94fa-c98dabcc5714'}
14:40:44 DEBUG service[299] ReportPortal - End TestSuite: request_body={'end_time': '1585597244033', 'issue': {'issue_ty
pe': 'ti001'}, 'item_id': '1e9b68ae-327a-4a55-b09b-13e944887694', 'status': 'FAILED'}
14:40:44 DEBUG connectionpool[393] http://<my instance>:8080 "PUT /api/v2/<my project>/item/1e9b68ae-327a-4a55-b09b-13e944887694
 HTTP/1.1" 200 93
14:40:44 DEBUG service[263] finish_test_item - ID: 1e9b68ae-327a-4a55-b09b-13e944887694
----------------------------------------------- live log sessionfinish ------------------------------------------------
14:40:44 DEBUG service[312] ReportPortal - Finish launch: request_body={'end_time': '1585597244049', 'status': None}
14:40:44 DEBUG connectionpool[393] http://<my instance>:8080 "PUT /api/v1/<my project>/launch/61119323-de50-40ca-b286-45dd09094e
d4/finish HTTP/1.1" 200 116
14:40:44 DEBUG service[188] finish_launch - ID: 61119323-de50-40ca-b286-45dd09094ed4


================================== FAILURES ===================================
______________________________ test_failing_test ______________________________

    @pytest.mark.marker1
    @pytest.mark.marker3
    def test_failing_test():
>       assert False
E       assert False

test_rp.py:17: AssertionError
=========================== short test summary info ===========================
FAILED test_rp.py::test_failing_test - assert False
========================= 1 failed, 2 passed in 0.23s =========================

C:\Users\my_user\Projects\Scratch\rp_test_project>
```

**Problem 1:**
Tags do not appear to work. As I understand it, the custom markers should be applied to the tests as tags. Additionally, I have specified a launch tag, but it does not appear as well.

I did some debugging, and found that the tags should be sent if the method `update_test_item` is on the client, but it does not appear to be. Looking at the client, that method is only in the v3 branch, not any release off of the `master` branch. Is this an upcoming feature?

**Problem 2:**
When I run this against my instance, the all 3 tests are marked as failed, even though only 1 of the 3 should. Any idea why this is happening?

I don't see why this is happening. This appears to be an error, but quizzically, does not appear to happen with another test run I have.

**Note:**
Apologies for the substitutions, but I did not want to give specific information from our environment. I can tell you that our locally hosted instance I am testing with is running RP 5.0.0. `pytest-reportportal` and `reportportal-client` are the latest released versions installed from PyPI.

**Comment by dijital20** [comment] 2020-03-30 19:55
Let me know if Problem 2 needs to be spun off as its own issue.

**Comment by iivanou** [comment] 2020-03-31 07:52
@dijital20 Hi. Problem #1 is gonna be fixed. tags are not accepted by the RP API anymore. We should use attributes instead. I did not get your second problem...

**Comment by dijital20** [comment] 2020-03-31 13:42
![image](https://user-images.githubusercontent.com/4934523/78032933-5e3c0080-732b-11ea-80a4-004d1f2c6a34.png)

Here's what the results of this test look like on our local instance, which shows Problem #2.

Noted that `test1` and `test2` should be passing, and `test_failing_test` should be failed... but all 3 show as failed.

**Comment by dijital20** [comment] 2020-03-31 13:43
On problem 1... should the documentation be updated then to show that tags are no longer supported?

**Comment by iivanou** [comment] 2020-03-31 13:56
Tags will be fixed in the next release(See #175). It requires updating the client as well. The second problem has already been fixed in #168.

**Comment by dijital20** [comment] 2020-03-31 14:32
Good deal. I understand if there's not an answer on this yet, but do you have an ETA on that release?

**Comment by iivanou** [comment] 2020-04-01 06:51
Both packages will be released once the mentioned PRs are approved.

**Comment by iivanou** [comment] 2020-04-02 11:45
@dijital20 Can you try 5.0.1 version to confirm that the issue is fixed?

**Comment by dijital20** [comment] 2020-04-02 13:15
Well, now there's a new problem. I updated the client (5.0.2) and plugin (5.0.1) and now I am getting a 400 Incorrect Request when it tries to StartTestItem.

[take2.log](https://github.com/reportportal/agent-python-pytest/files/4421251/take2.log)

**Comment by iivanou** [comment] 2020-04-02 14:47
Fixed in 5.0.2 release.

**Closed** 2020-04-02 15:11 UTC
Labels: bug

**Comment by dijital20** [comment] 2020-04-02 16:48
Fix one bug, find another one.

[take3.log](https://github.com/reportportal/agent-python-pytest/files/4422367/take3.log)

**Comment by dijital20** [comment] 2020-04-02 16:51
Well, hrm... it didn't happen the other 2 times. Disregard I suppose.
