### ISSUE TITLE
ReportPortalServiceAsync class missing a few attributs - errors return  

### ISSUE THREAD

**Issue by trew100** [reportportal/agent-python-pytest#112] opened 2019-05-06 17:08 UTC
### The first issue
In the service.py file class initial with `verify_ssl` argument
```
self.RP = ReportPortalServiceAsync(
                endpoint=endpoint,
                project=project,
                token=uuid,
                error_handler=self.async_error_handler,
                log_batch_size=log_batch_size,
                verify_ssl=verify_ssl
            )
```  
there is no `verify_ssl` parameter for ReportPortalServiceAsync class
as you can see 
```
class ReportPortalServiceAsync(object):
    """Wrapper around service class to transparently provide async operations
    to agents.
    """

    def __init__(self, endpoint, project, token, api_base="api/v1",
                 error_handler=None, log_batch_size=20):
```

this problem create this error 
```

pyest project-tests\tests\suit_basic_tests.py --reportportal
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\main.py", line 207, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\plugin.py", line 57, in pytest_sessionstart
INTERNALERROR>     verify_ssl=session.config.getini('rp_verify_ssl')
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\service.py", line 97, in init_service
INTERNALERROR>     verify_ssl=verify_ssl
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'verify_ssl'
```

### The second issue
the same place in service.py
after ReportPortalServiceAsync class initial the code try to call to `get_project_settings` function
it look like this
```
self.RP = ReportPortalServiceAsync(
                endpoint=endpoint,
                project=project,
                token=uuid,
                error_handler=self.async_error_handler,
                log_batch_size=log_batch_size,
                # verify_ssl=verify_ssl
            )
self.project_settiings = self.RP.rp_client.get_project_settings() if self.RP else None
self.issue_types = self.get_issue_types()
```
this method doesn't exist in the ReportPortalServiceAsync class
while running this error return
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\_pytest\main.py", line 207, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\plugin.py", line 57, in pytest_sessionstart
INTERNALERROR>     verify_ssl=session.config.getini('rp_verify_ssl')
INTERNALERROR>   File "c:\users\myuser\appdata\local\programs\python\python36-32\lib\site-packages\pytest_reportportal\service.py", line 100, in init_service
INTERNALERROR>     self.project_settiings = self.RP.rp_client.get_project_settings() if self.RP else None
INTERNALERROR> AttributeError: 'ReportPortalService' object has no attribute 'get_project_settings'
```

**Comment by iivanou** [comment] 2019-10-03 07:11
This is a duplicate of https://github.com/reportportal/agent-python-pytest/issues/111.

@trew100, try the latest version of the reportportal-client.

**Closed** 2020-01-22 14:37 UTC
Labels: duplicate
