### ISSUE TITLE
reported log level by file

### ISSUE THREAD

**Issue by bivas6** [reportportal/agent-python-pytest#216] opened 2020-07-22 15:16 UTC
Hi,

Is there a way to specify global logging level to report on [Error] and override it in specific files?

We are using a lot of pip-packages that filled us with debug/info logging, while we are interested only in our logs.

Thanks.

**Comment by iivanou** [comment] 2020-07-22 15:37
Currently, the agent filters out the reportportal_client messages only. And there is no option to add additional loggers that need to be excluded. This functionality either needs to be implemented in the agent or you can disable logging from other packages in your code.

**Comment by bivas6** [comment] 2020-07-23 08:43
Thanks for the quick reply!

My problem is that before I used report-portal, i have those lines in conftest.py:

`import logging
logging.basicConfig(level=logging.ERROR)
`
Which cause every package to log only errors, but now it seems that report-portal agent just override it somehow.

Thanks.

**Comment by iivanou** [comment] 2020-07-23 09:04
I do not see any changes related to logging being submitted this year... Check your fixtures and Pytest command-line options.

**Comment by bivas6** [comment] 2020-07-23 15:55
OK, So I managed to reproduce it with a minimal project:

File pytest.ini:
```
[pytest]

log_cli = true
log_level = ERROR
log_cli_level = ERROR
rp_uuid = <uuid>
rp_endpoint = <endpoint>
rp_project = <project>
rp_launch = <launch>
```

File test_somthing.py:
```
import logging
logger = logging.getLogger(__name__)

def test_foo():
    logger.debug('this is DEBUG')
    logger.info('this is INFO')
    logger.warning('this is WARNING')
    logger.error('this is ERROR')
    assert True
```

File run.py:
```
import pytest
import logging
logging.basicConfig(level=logging.ERROR)

pytest.main(['--reportportal', '-s'])
```
and execute:
`python3 run.py`

Output:
```
:~/example$ python3 run.py 
============= test session starts ==============================================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.8.1, pluggy-0.13.0
rootdir: /example, inifile: pytest.ini
plugins: html-2.1.1, ordering-0.6, metadata-1.9.0, reportportal-5.0.3, asyncio-0.14.0
collected 1 item                                                                                                                                                                                                                

test_somthing.py::test_foo DEBUG:test_somthing:this is DEBUG
DEBUG:urllib3.connectionpool:http://<endpoint>:8080 "POST /api/v2/superadmin_personal/log HTTP/1.1" 201 45
DEBUG:reportportal_client.service:log - ID: 4b6a43b7-74b1-4b79-ab92-393487bfe2e7
INFO:test_somthing:this is INFO
DEBUG:urllib3.connectionpool:http://<endpoint>:8080 "POST /api/v2/superadmin_personal/log HTTP/1.1" 201 45
DEBUG:reportportal_client.service:log - ID: 4b6a43b7-74b1-4b79-ab92-393487bfe2e7
WARNING:test_somthing:this is WARNING
DEBUG:urllib3.connectionpool:http://<endpoint>:8080 "POST /api/v2/superadmin_personal/log HTTP/1.1" 201 45
DEBUG:reportportal_client.service:log - ID: 4b6a43b7-74b1-4b79-ab92-393487bfe2e7
ERROR:test_somthing:this is ERROR

--------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------
ERROR    test_somthing:test_somthing.py:8 this is ERROR
DEBUG:urllib3.connectionpool:http://<endpoint>:8080 "POST /api/v2/superadmin_personal/log HTTP/1.1" 201 45
DEBUG:reportportal_client.service:log - ID: 4b6a43b7-74b1-4b79-ab92-393487bfe2e7
PASSED
==================== 1 passed in 0.20s ====================
```

But if I'm changing pytest execution in run.py to:
`pytest.main(['-s'])`

Only the ERROR logs are displayed.

Thanks.

**Comment by iivanou** [comment] 2020-07-24 12:54
@bivas6 If you are using the rp_logger fixture described in the [docs](https://github.com/reportportal/agent-python-pytest#examples) **as is**, it is expected to have the log level being changed with the reportportal option enabled.

**Comment by iivanou** [comment] 2020-07-24 13:09
Was not able to reproduce your issue on my environment.
![image](https://user-images.githubusercontent.com/8349078/88394375-076da180-cdc8-11ea-98be-2b01cd57484b.png)

**Comment by bivas6** [comment] 2020-07-26 15:46
This way it works also for me as expected.
The problem reproduced when you are trying to run pytest from python script (see run.py above).

**Comment by iivanou** [comment] 2020-07-27 09:45
@bivas6 The basicConfig function does nothing if the root logger already has handlers configured. If case of starting your script with the --reportportal option, you should change log level the following way:

`logging.getLogger('').setLevel('ERROR')`

P.S. The way you are running pytest is not officially supported:)

**Comment by bivas6** [comment] 2020-07-27 11:58
OK, I see, thanks.

P.S. Why not? [Docs](https://docs.pytest.org/en/stable/usage.html#calling-pytest-from-python-code)

**Comment by orgads** [comment] 2020-08-25 06:08
@iivanou Hi,

Can you suggest a fix or a workaround for this?

**Comment by iivanou** [comment] 2020-08-25 07:38
@bivas6 Read [this](https://docs.python.org/3/library/logging.html#logging.basicConfig) out, please.

@orgads Workaround is posted in [this](https://github.com/reportportal/agent-python-pytest/issues/216#issuecomment-664245575) comment.

**Comment by iivanou** [comment] 2021-02-15 14:34
Closing this one. Feel free to re-open the issue if it is still actual.

**Closed by iivanou** 2021-02-15 14:34 UTC
