### ISSUE TITLE
reportportal_client.errors.ResponseError: 40023

### ISSUE THREAD

**Issue by DKorytkin** [reportportal/agent-python-pytest#26] opened 2017-06-26 13:25 UTC
```
platform linux -- Python 3.5.2, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/dkorytkin/PycharmProjects/test/tests, inifile: pytest.ini
plugins: reportportal-1.0.0, env-0.6.2, allure-pytest-2.0.0b1
collected 1 items 

tests/test_open_page.py .

```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/reportportal_client/service.py", line 140, in finish_launch
    return _get_msg(r)
  File "/usr/local/lib/python3.5/dist-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/usr/local/lib/python3.5/dist-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: 40023: Finish launch is not allowed. Launch '595100c1b9d82100058c4dfe' has items '[595100c1b9d82100058c4e00]' with 'IN_PROGRESS' status```

**Comment by krasoffski** [comment] 2017-07-04 08:33
It would be great to have a code snippet how to reproduce this issue.

Thanks,

**Comment by DzmitryHumianiuk** [comment] 2017-07-07 15:54
@DKorytkin coul you please share a simple code snippet how to reproduce this issue?

**Comment by PositiveAlex** [comment] 2017-09-07 01:15
For me this could be faced in two cases:

- parallel execution: one launch ends first while second still running.
- fixed launch id plus two separate test runs.

**Comment by 132u** [comment] 2017-10-24 07:17
The same bug is stable reproduced for me when some method which is executed after scenario in Hook class throws NullRefrence exception. It is really annoying because Launc is hang and interrupted and then we can not use Analysis feature :(

**Comment by schandrakandi** [comment] 2018-03-01 06:37
i am facing the same issue with robot framework. Is there any fix for this.


01-Mar-2018 04:45:48 | [u'--test', u'TestWan', u'--outputdir', '/root/bamboo-agent-home/xml-data/build-dir/AUTNG-AUT-JOB1', '--variable', 'AUTONG_HOME:/root/bamboo-agent-home/xml-data/build-dir/AUTNG-AUT-JOB1', '--listener=reportportal_listener', '--variable', 'RP_UUID:99c37ef8-16e6-4c9b-902c-0dda30363a5f', '--variable', 'RP_ENDPOINT:http://auto-ng-report-portal:8080', '--variable', 'RP_LAUNCH:Auto-NG-SCM_Sanity', '--variable', 'RP_PROJECT:scm_sanity', '--pythonpath', '/root/bamboo-agent-home/xml-data/build-dir/AUTNG-AUT-JOB1/libraries/GUI', '/root/bamboo-agent-home/xml-data/build-dir/AUTNG-AUT-JOB1/tests/sanity/sampletest/test_wan.robot']
-- | --
01-Mar-2018 04:45:48 | ==============================================================================
01-Mar-2018 04:45:48 | Test Wan
01-Mar-2018 04:45:48 | ==============================================================================
01-Mar-2018 04:45:49 | Suite Test Wan (s1) starting.
01-Mar-2018 04:45:49 | Suite Test Wan (s1) starting.
01-Mar-2018 04:45:49 | Suite Test Wan (s1) starting.
01-Mar-2018 04:45:49 | Suite Test Wan (s1) starting.
01-Mar-2018 04:47:06 | TestWan :: Sample work flow test for testing Wan.                     \| FAIL \|
01-Mar-2018 04:47:06 | TimeoutException: Message:
01-Mar-2018 04:47:06 | ------------------------------------------------------------------------------
01-Mar-2018 04:47:06 | [ ERROR ] Calling method 'end_suite' of listener 'reportportal_listener' failed: ResponseError: 40023: Finish launch is not allowed. Launch '5a97857d24aa9a0001ae7f69' has items '[5a97857d24aa9a0001ae7f6b]' with 'IN_PROGRESS' status
01-Mar-2018 04:47:06 | Test Wan                                                              \| FAIL \|
01-Mar-2018 04:47:06 | 1 critical test, 0 passed, 1 failed
01-Mar-2018 04:47:06 | 1 test total, 0 passed, 1 failed

**Comment by DzmitryHumianiuk** [comment] 2018-07-17 15:37
@schandrakandi try to find community members help for this issue in our slack
https://reportportal-slack-auto.herokuapp.com/

channel `#agent_python`

**Closed** 2020-03-19 14:02 UTC
Labels: wontfix
