### ISSUE TITLE
Plugin crash on connection error

### ISSUE THREAD

**Issue by liiight** [reportportal/agent-python-pytest#158] opened 2020-01-22 14:01 UTC
I got the following crash: 

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pytest_reportportal/plugin.py", line 53, in pytest_sessionstart
INTERNALERROR>     retries=int(session.config.getini('retries')),
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pytest_reportportal/service.py", line 117, in init_service
INTERNALERROR>     self.issue_types = self.get_issue_types()
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/pytest_reportportal/service.py", line 348, in get_issue_types
INTERNALERROR>     for item in self.project_settings["subTypes"][item_type]:
INTERNALERROR> KeyError: 'subTypes'
```

Seems that due to a connection issue, this is the content that I got for `self.project_settings`: `{'errorCode': 4003, 'message': 'You do not have enough permissions. Access is denied'}`

Since there was no error check on the response in `get_project_settings()` the error response was just passed as dict via `_get_json`.

RP version: 5.0.0
pytest-reportportal-1.0.9

**Comment by iivanou** [comment] 2020-01-22 14:27
@liiight Currently RP version  5.0.0 is not supported by Python agents. The problem you are seeing is about permission issues rather than connection. Actually, the agent has been connected to the RP but failed to get your project setting due to the incorrect token or project name. The format of the JSON for the failure has changed in report portal version 5.0.0 and is not correctly handled by the current implementation of the agent.

**Comment by liiight** [comment] 2020-01-22 15:23
I see. Are you planning to update the client to work with v5.0?

**Comment by iivanou** [comment] 2020-01-22 15:29
Yep, we are planning.

**Comment by liiight** [comment] 2020-01-22 21:02
Awesome. Thank you for RP and this plugin!

**Comment by liiight** [comment] 2020-01-24 21:41
Can you please specify on the last RP version that is supported? Also, I'd recommend adding this to the README

**Comment by iivanou** [comment] 2020-01-27 07:19
Everything except RP version 5.0 is supported.

**Comment by liiight** [comment] 2020-01-27 07:25
I'd like to contribute in making this happen. I want to use RP and I see that older docker images of it are no longer available.

I'll start whipping up a PR

**Comment by iivanou** [comment] 2020-03-19 13:53
@liiight Can you try to reproduce the issue with the latest version of the agent? Let's try to close this...

**Comment by HardNorth** [comment] 2021-12-23 13:21
The issue is not reproducible with `rp_ignore_errors = True`. However this flag is absolutely redundant. We are reporting tool and should not fail by default.

**Closed by HardNorth** 2021-12-23 13:21 UTC
Labels: need more information
