### ISSUE TITLE
reportportal_client.errors.Error: Service already stopped.

### ISSUE THREAD

**Issue by DKorytkin** [reportportal/agent-python-pytest#28] opened 2017-06-26 15:13 UTC
```python
platform linux -- Python 3.5.2, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/dkorytkin/my_work/marketplace, inifile: pytest.ini
plugins: reportportal-1.0.0, env-0.6.2
collected 7 items 

test_marketplace_catalog_main_page.py ..
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/main.py", line 164, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/runner.py", line 60, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     nextitem=nextitem))
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/runner.py", line 129, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/plugin.py", line 55, in pytest_runtest_makereport
INTERNALERROR>     PyTestService.finish_pytest_item(item_result)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/service.py", line 116, in finish_pytest_item
INTERNALERROR>     self.RP.finish_test_item(**fta_rq)
INTERNALERROR>   File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/reportportal_client/service_async.py", line 256, in finish_test_item
INTERNALERROR>     self.queue.put_nowait(("finish_test_item", args))
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'put_nowait'
Traceback (most recent call last):
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/config.py", line 58, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/main.py", line 134, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/main.py", line 128, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/terminal.py", line 386, in pytest_sessionfinish
    outcome.get_result()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/plugin.py", line 77, in pytest_sessionfinish
    PyTestService.finish_launch(status="RP_Launch")
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/service.py", line 126, in finish_launch
    self.RP.finish_launch(**fl_rq)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/reportportal_client/service_async.py", line 233, in finish_launch
    self.queue.put_nowait(("finish_launch", args))
AttributeError: 'NoneType' object has no attribute 'put_nowait'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/config.py", line 60, in main
    config._ensure_unconfigure()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/config.py", line 917, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/plugin.py", line 92, in pytest_unconfigure
    PyTestService.terminate_service()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/pytest_reportportal/service.py", line 54, in terminate_service
    self.RP.terminate()
  File "/home/dkorytkin/.local/share/virtualenvs/marketplace-Gls_8Zt3/lib/python3.5/site-packages/reportportal_client/service_async.py", line 153, in terminate
    raise Error("Service already stopped.")
reportportal_client.errors.Error: Service already stopped.```

**Comment by krasoffski** [comment] 2017-06-28 05:57
Closed as duplicate of Issue #24

**Closed by krasoffski** 2017-06-28 05:57 UTC
