### ISSUE TITLE
Log level are not getting set and logging happens in the testcases when run.

### ISSUE THREAD

**Issue by ohank** [reportportal/agent-python-pytest#230] opened 2020-09-23 08:10 UTC
Background 
 
When using report portal each line in a test case that include some sort of communication towards DUT add test time. This can be a serious bug if it leads to that the test fails due to timeout. It can also be difficult to make the conclusion that it depends to using report portal. 

When inspecting the logs that is created is show that it has both log level INFO and DEBUG. It shall not have any DEBUG information due to that the default setup file for report portal with pytest is used and it is specified to only add INFO level of information. 

Using:
report portal v5.1
pytest-reportportal 5.0.3
reportportal-client 5.0.3 

Default setup file 

 from pytest_reportportal import RPLogger, RPLogHandler 

    logger = logging.getLogger(__name__) 

    logger.setLevel(logging.INFO) 

    # Create handler for Report Portal if the service has been 

    # configured and started. 

    if hasattr(request.node.config, 'py_test_service'): 

        # Import Report Portal logger and handler to the test module. 

        logging.setLoggerClass(RPLogger) 

        rp_handler = RPLogHandler(request.node.config.py_test_service) 

        # Add additional handlers if it is necessary 

        console_handler = logging.StreamHandler(sys.stdout) 

        console_handler.setLevel(logging.INFO) 

        logger.addHandler(console_handler) 

    else: 

        rp_handler = logging.StreamHandler(sys.stdout) 

    # Set INFO level for Report Portal handler. 

    rp_handler.setLevel(logging.INFO) 

    return logger 

Steps to reproduce 
1. Run a test that has some communication with DUT with report portal on. 

2. Repeat the test with modified pytest_reportportal source code i.e.  
Changed the logging.NOTSET to logging.INFO (i.e. now hardcoded) 

![image](https://user-images.githubusercontent.com/44366788/93984078-a93b4b80-fd83-11ea-883a-956a6f08e45b.png)

3. Repeat the test with report portal off. 

4. Compare logs for example when setting or reading a value from IO.  
    With the modified source code of report portal the communication takes less time than it does if it is not modified. When 
 report portal is turned off the test case executes faster. 

Actual Result 

When the logs from the three test runs are compared it is clear that when  
test results are sent to report portal it adds time for each communication. 

With report portal: 
![image](https://user-images.githubusercontent.com/44366788/93984431-14851d80-fd84-11ea-9901-63b7e9e06ac4.png)

 

Below is the INFO level log. 
 ![image](https://user-images.githubusercontent.com/44366788/93984411-0df6a600-fd84-11ea-9846-610957bd4e55.png)

 

 

 

 

 

Below is the Debug level log 
![image](https://user-images.githubusercontent.com/44366788/93984453-1cdd5880-fd84-11ea-9efe-fd2871c7dc49.png)

 
 

The “Debug level” shall not include any more information than the “Info level” due to that only “Info level” is set in the report portal setup file. 

With modified pytest_reportportal source code. 
![image](https://user-images.githubusercontent.com/44366788/93984477-236bd000-fd84-11ea-9664-3edc4ead88dd.png)

 

Below is the Info level log 
![image](https://user-images.githubusercontent.com/44366788/93984494-2a92de00-fd84-11ea-87f8-4b833245118f.png)

 

Below is the Debug level log 
![image](https://user-images.githubusercontent.com/44366788/93984525-32eb1900-fd84-11ea-8be9-df748ae7649e.png)

 

With no report portal: 
![image](https://user-images.githubusercontent.com/44366788/93984534-35e60980-fd84-11ea-97fe-4df265bfdfee.png)

Expected result
Using report portal shall not add any time inside a test case.

**Comment by ohank** [comment] 2020-09-23 08:11
Time for whole test sequence to execute will be added soon.

**Comment by iivanou** [comment] 2020-10-06 14:47
It's not possible to "not add any time" to a test execution when adding more code that works with RP API. The root cause of that issue is described [here](https://github.com/reportportal/client-Python/issues/113). Will be fixed when the mentioned issue is closed and released.

**Closed by iivanou** 2020-10-06 14:47 UTC

**Comment by ohank** [comment] 2020-10-06 17:34
We did fix the by changing our on pytest plugin for report portal.
