### ISSUE TITLE
WARNING Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by clacroix12** [reportportal/agent-python-pytest#248] opened 2021-01-27 19:53 UTC
Hello,

My team has been using an older version of pytest-reportportal with our ReportPortal v4 instance for a while now with some level of success. We have recently been provided with a v5.3.0 ReportPortal instance so I am trying to update to the later pytest-reportportal agent version which is compatible. During testing I have been encountering the following error being spammed until my application/pytest process is killed:

```
22:58:36 - MainThread - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: <instance_url>
22:58:36 - MainThread - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: <instance_url>
22:58:36 - MainThread - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: <instance_url>
22:58:36 - MainThread - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: <instance_url>
22:58:36 - MainThread - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: <instance_url>
```

I tried adding DEBUG information but the only thing I could see was the following message between the warnings:
```
13:27:03 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (846): <instance_url>
```

This warning is spammed about a dozen times a second until the process is killed. I have tried adjusting the `rp_log_batch_size` from anywhere between 50 and 250 with no change in behavior.

I am executing this from macOS 10.15.7 however I have seen the exact same behavior from one of my team's jenkins slaves running CentOS 7 so I do not believe this is a local/OS issue.

pytest-reportportal==5.0.7
reportportal-client==5.0.7
pytest==5.3.5

Any help troubleshooting this would be greatly appreciated, thanks.

**Comment by iivanou** [comment] 2021-01-28 14:01
Hi, the issue occurs if you send too many attachments to RP. Caused by [this bug](https://github.com/reportportal/client-Python/issues/113).

**Comment by clacroix12** [comment] 2021-01-28 23:36
> Hi, the issue occurs if you send too many attachments to RP. Caused by [this bug](https://github.com/reportportal/client-Python/issues/113).

I don't think this is limited to attachments as none of the log messages we are sending to RP have any attachments:

![Screen Shot 2021-01-28 at 3 35 59 PM](https://user-images.githubusercontent.com/1605721/106212019-8d571480-617e-11eb-8c65-c1a7405a0aa5.png)

**Comment by DzmitryHumianiuk** [comment] 2021-01-29 17:22
@clacroix12 please also take a look into configuration of connection pool here
https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-application-connections-pool-tuning

**Comment by clacroix12** [comment] 2021-02-05 00:04
> @clacroix12 please also take a look into configuration of connection pool here
> https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-application-connections-pool-tuning

Thanks, I'll pass this onto the team that maintains the RP instance and see if some adjustments can alleviate this issue.

In the meantime I've been trying to mess with the logging batch size to try to cut down on the amount of connections necessary while logging in large amounts. It appears that it isn't batching logs at all. I'm seeing POSTs to the `/api/v2/superadmin_personal/log` API endpoint for each and every log message in my test. Shouldn't logs be being posted in batches? By default the `log_batch_size` is set to 20 for the `ReportPortalService` and I have it configured to 50 in my `pytest.ini`. Unless I'm misunderstanding the configuration setting it seems like my logs aren't being batched at all.

**Comment by iivanou** [comment] 2021-03-02 13:17
@clacroix12, Can we close it?

**Comment by clacroix12** [comment] 2021-03-09 23:21
It doesn't seem like this is an issue with the pytest agent itself so we can close this one out.

**Comment by iivanou** [comment] 2021-03-10 08:44
@clacroix12 It was an issue with the client. Log batches had not been working for some time.

**Comment by clacroix12** [comment] 2021-06-08 20:08
@iivanou I am reopening this issue because I am still seeing this on report portal 5.3.5 and I was able to reproduce it on demo.reportportal.io. The launch/logs have been deleted by now but I can run a simple test (see below) to reproduce it. The test code that I used to reproduce this issue is simply logging a few times every second for a minute. You can adjust the duration if necessary but I was usually able to hit this issue in under a minute at this rate.

One thing I'm not sure of is if this stops the execution from recovering and eventually being able to post to report portal again. Given the amount of noise this issue creates that was difficult for me to verify. I'm not sure if suppressing this warning is the right call, or if the agent should see this and back off trying to establish a connection for a short duration, but I believe something needs to be done on the agent side of things here.


Test code:
```python
import time
import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger(__name__)


def test_report_portal_logging():
    duration = 60
    start_time = time.time()
    current_time = time.time()

    while current_time - start_time < duration:
        current_time = time.time()
        run_time = int(current_time - start_time)

        logger.info("start time: %s", start_time)
        logger.info("current time: %s", current_time)
        logger.info("run time: %s", run_time)
        time.sleep(1)

    logger.info("Completed the test")
    ```

**Comment by petr-balogh** [comment] 2021-07-01 15:17
Hello @iivanou , can you please take a look? We need to really move with this issue. Thanks!

**Comment by iivanou** [comment] 2021-07-05 16:32
Is that reproducible with the latest version of packages? Have you tried playing with max_pool_size?

**Comment by clacroix12** [comment] 2021-07-07 22:56
> Is that reproducible with the latest version of packages(pytest-reportportal, reportportal-client)? Have you tried playing with max_pool_size?

I believe I was using the latest versions when I reproduced it last, however I can re-verify that is the case with the current latest versions. Is there an easy way to manipulate the `max_pool_size` through the pytest agent or is that something I need to change manually in the underlying python client?

**Comment by clacroix12** [comment] 2021-07-09 22:59
@iivanou I have reproduced the issue using the test case I commented above with the following agent/client versions:

```
pytest-reportportal==5.0.10
reportportal-client==5.0.12
```

**Comment by HardNorth** [comment] 2022-01-05 12:51
Hmm, I'm not able to reproduce that with the latest versions:
```
pytest-reportportal==5.0.10
reportportal-client==5.1.0
```
Unless I'll get a reproducible example I count that as fixed.

**Closed by HardNorth** 2022-01-05 12:51 UTC
Labels: bug
